# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HFProjectPlayground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # Pods for HFProjectPlayground

  target 'HFProjectPlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HFProjectPlaygroundUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
