# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HFPlaygrounds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for HFPlaygrounds

  target 'HFPlaygroundsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HFPlaygroundsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
